### ISSUE TITLE
Creating Input Page

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#11]
Created a main page where CRUD is intergrated and executed by user input.

**Comment by Celio121** [comment]
Created input file but needing to intergrate CRUD executions

**Comment by Celio121** [comment]
# User input output
def consoleInput():
    print(
        """
        Welcome to the Key Inventory!
        Please select an option by entering the number.
        1. Create a new entry
        2. Get all data on DB
        3. Update a row in the database
        4. Delete a row from the database
        """
        )
    choice = input("Please enter an option: ")
# Choice selection from user input

**Comment by DevvyP** [comment]
Hi Celio,

That is fine to do but you will still need to add an input to select the which statement to use. I would recommend first creating the statements in a file then importing them into this file.

**Comment by Celio121** [comment]
This is the selection in which you will have to select the number to execute the correct code I have imported the data from the CRUD file as this is where all the executable code resides. 

#importing all the executable code from other files
from setup import createConn
from services import getAllData
from CRUD import createRowConsole, deleteOneConsole, updateOneConsole



    if choice == "1":
        createRowConsole(conn)
    elif choice == "2":
        print(getAllData(conn, 'key_inv'))
    elif choice == "3":
        updateOneConsole(conn)
    elif choice == "4":
        deleteOneConsole(conn)

consoleInput()

This will run the consoleInput and display the options to the user then ask for and input.

**Comment by DevvyP** [comment]
This is looking good Celio I have nothing to complain about this.
