### ISSUE TITLE
CRUD - Create

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#12]

**Comment by Celio121** [comment]
So first I have to create the code to create a row and add an exception incase there is an incorrect value added into the table.

# code to create a data entry to database
def createRow(conn, query):
    try:
        conn.cursor().execute(query)
        conn.commit()
        return True
    except Exception as e:
        print(str(e))
        print("An exception happened:(")
    finally:
        print("This will always run, regardless of whether there is an exception or not")

Once this is done I will create the table in the database with a Key id, Room id, Rack id, and contained fields.

from setup import createConn, createTable

# defining connection and cursor
conn = createConn('key_dbase.db')
cursor = conn.cursor()

# create key table
create_keytable = "CREATE TABLE IF NOT EXISTS key_inv (key_id INTERGER NOT NULL UNIQUE, room_id int(5) NOT NULL, rack varchar(5) NOT NULL, contained bool NOT NULL, PRIMARY KEY(key_id));"
createTable(conn, create_keytable)

After the table is created it will prompt the user to add the values that are needed into these fields.

from services import createRow, deleteByid, getAllData, updateByid, getOneRow

def createRowConsole(conn):
    key = input("Please enter key id: ")
    room = input("Please enter room location: ")
    rack = input("Please enter rack location: ")
    contained = input("Is the key in the safe(True/False): ")
    query = f"INSERT INTO key_inv VALUES({key}, {room},'{rack}',{contained});"

    createRow(conn, query)

Once this is done the values are commited into the database and will not be lost unless removed.

**Comment by DevvyP** [comment]
This is looking good Celio, I willl say something for future reference 

create_keytable = "CREATE TABLE IF NOT EXISTS key_inv (key_id INTERGER NOT NULL UNIQUE, room_id int(5) NOT NULL, rack varchar(5) NOT NULL, contained bool NOT NULL, PRIMARY KEY(key_id));"
createTable(conn, create_keytable)

This works but is really annoying to read if you have multiple lines of code. The best thing I would suggest is to space it out, by what I mean is to do this.

create_keytable = """CREATE TABLE IF NOT EXISTS key_inv
(key_id INTERGER NOT NULL UNIQUE, 
room_id int(5) NOT NULL, 
rack varchar(5) NOT NULL, 
contained bool NOT NULL, 
PRIMARY KEY(key_id)
);"""
createTable(conn, create_keytable)

By doing this you are easily able to change and see what the name of the fields are. It is also easier to add more fields if needed.

**Comment by DevvyP** [comment]
Once you have done this all you need to do is link it to the input page by importing it and this is done.

**Comment by Celio121** [comment]
I have changed it and everything is linked to the input file. I will close this issue now
