### ISSUE TITLE
CRUD - Read

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#13]

**Comment by DevvyP** [comment]
This will display all the data in the table in the database. Not just one row.

# fetching inputted data from database
def getAllData(conn, tableName):

    # Displays columns
    print(f'\nColumns in {tableName} table:')
    cdata = conn.cursor().execute(f"""SELECT * FROM {tableName}""")
    for column in cdata.description:
        print(column[0])
    print(f'\nData in {tableName} table:')
    for row in cdata:
        print(row)
        return True

**Comment by Celio121** [comment]
fetching inputted data from database

def getAllData(conn, tableName):

# Displays columns
print(f'\nColumns in {tableName} table:')
cdata = conn.cursor().execute(f"""SELECT * FROM {tableName}""")
for column in cdata.description:
    print(column[0])
print(f'\nData in {tableName} table:')
for row in cdata:
    print(row)
    return True

**Comment by DevvyP** [comment]
Thanks for the tip. I have added this after creating the input file. This selects the ID of the key and displays only that key.

# returns one line of information from database
def getOneRow(conn, ids):
    rowInfo = conn.cursor().execute(f"""
        SELECT * 
        FROM key_inv 
        WHERE key_id ={ids}""")
    listRow = rowInfo.fetchall()
    return listRow

**Comment by Celio121** [comment]
Thanks for the tip. I have added this after creating the input file. This selects the ID of the key and displays only that key.
returns one line of information from database

def getOneRow(conn, ids):
rowInfo = conn.cursor().execute(f"""
SELECT *
FROM key_inv
WHERE key_id ={ids}""")
listRow = rowInfo.fetchall()
return listRow
