### ISSUE TITLE
CRUD - Update

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#14]

**Comment by Celio121** [comment]
# update key contained command
def updateByid(conn, ids, cont):
    conn.cursor().execute(f"""
    UPDATE key_inv
    SET contained = {cont}
    WHERE key_id = {ids};""")

this is in the services file and can not be executed

from services import createRow, deleteByid, getAllData, updateByid, getOneRow

# User input to update contained variable in database to define if key is in the safe or not. 

def updateOneConsole(conn):
    print("\nBelow is all the keys registered.")
    print(getAllData(conn, 'key_inv'))
    ids = input("""\nPlease state which key is taken out of the safe by selecting the ID: """) # User input key id
    print(f"""\nYou have selected the following Key ID: """ + str(getOneRow(conn, ids)))  # displays the current key selected.
    cont = input("""\nUpdate whether key is in the safe or not(True False): """) # user input contained value
    updateByid(conn, ids, cont) # updating key contained value
    conn.commit()
    print(getOneRow(conn, ids))

This will be the executeable code for the input file.

**Comment by DevvyP** [comment]
This is looking good so far Celio. Nothing to complain about this
