### ISSUE TITLE
CRUD - Delete

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#15]

**Comment by Celio121** [comment]
# cursor command to delete data from table
def deleteByid(conn, id):
    conn.cursor().execute(f"""
    DELETE FROM key_inv 
    WHERE key_id = {id};
    """)
    return True

This code is in the services file and can not be executed. 

# User input key id to delete row from table. Once deleted change is commited and data will be deleted.

def deleteOneConsole(conn):
    id = input("Please enter id of the key you would like to delete: ") # User input to define key id
    deleteByid(conn, id)
    conn.commit()
    print("""
    Deletion is a success!
    
    Displaying change in database after deletion below:
    """)
    print(getAllData(conn, 'key_inv'))

This code can be executed and will commit the changes to the database. I have added a get all data as this will display all the keys.

**Comment by DevvyP** [comment]
This looks good and I like how you print all the keys to ensure it has been deleted.
