### ISSUE TITLE
Testing code

### ISSUE THREAD

**Issue by Celio121** [Celio121/CRUD_App#16]

**Comment by Celio121** [comment]
![Image](https://user-images.githubusercontent.com/110827991/221199622-9078c1d8-f01d-4eb7-9867-cb5954b5751f.PNG)

**Comment by Celio121** [comment]
these are replica files of the original files to test all the definitions using pytest

**Comment by Celio121** [comment]
from test_services import createRow, deleteByid, getAllData, updateByid, getOneRow
import sqlite3
import pytest

# User definition to create new row

def createRowConsole(conn):
    key = input("Please enter key id: ")
    room = input("Please enter room location: ")
    rack = input("Please enter rack location: ")
    contained = input("Is the key in the safe(True/False): ")
    query = f"INSERT INTO key_inv VALUES({key}, {room},'{rack}',{contained});"

    createRow(conn, query)

# Testing data creation definition
def test_createRowConsole():
    # Set up
    conn = sqlite3.connect(':memory:')
    cursor = conn.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS test_table
    (key_id INTERGER NOT NULL UNIQUE, 
    room_id int(5) NOT NULL, 
    rack varchar(5) NOT NULL, 
    contained bool NOT NULL, 
    PRIMARY KEY(key_id)
    );""")

    #test code
    key = 1
    room = 2
    rack = 3
    contained = True
    query = f"INSERT INTO test_table VALUES({key}, {room},'{rack}',{contained});"

    createRow(conn, query)

    #show results
    result = cursor.execute("""SELECT * FROM test_table""").fetchone()
    assert result == (1, 2, '3', True)

# User input key id to delete row from table. Once deleted change is commited and data will be deleted.
def deleteOneConsole(conn):
    id = input("Please enter id of the key you would like to delete: ")
    deleteByid(conn, id)
    conn.commit()
    print("""
    Deletion is a success!
    
    Displaying change in database after deletion below:
    """)
    print(getAllData(conn, 'key_inv'))

# Testing delete definition
def test_deleteOneConsole():
    # Creation
    conn = sqlite3.connect(':memory:')
    cursor = conn.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS test2
    (id INTERGER NOT NULL UNIQUE,
    cont bool NOT NULL
    );""")
    data_ins = createRow(conn, f"INSERT INTO test2 VALUES(2, True);")
    data_ins2 = createRow(conn, f"INSERT INTO test2 VALUES(3, False);")
    input = 2
    delete_data = cursor.execute(f"""DELETE FROM test2 
    WHERE id = {input};
    """)
    # Result
    result = cursor.execute(f"""SELECT * FROM test2""").fetchone()
    # Assert
    assert result == (3, False)

# User input to update contained variable in database to define if key is in the safe or not.
def updateOneConsole(conn):
    print("\nBelow is all the keys registered.")
    print(getAllData(conn, 'key_inv'))
    ids = input("""\nPlease state which key is taken out of the safe by selecting the ID: """) # User input key id
    print(f"""\nYou have selected the following Key ID: """ + str(getOneRow(conn, ids)))  # displays the current key selected.
    cont = input("""\nUpdate whether key is in the safe or not(True False): """) # user input contained value
    updateByid(conn, ids, cont) # updating key contained value
    conn.commit()
    print(getOneRow(conn, ids))

# Testing update definition
def test_updateOneConsole():
    # Creation
    conn = sqlite3.connect(':memory:')
    cursor = conn.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS test2
    (id INTERGER NOT NULL UNIQUE,
    cont bool NOT NULL
    );""")
    data_ins = createRow(conn, f"INSERT INTO test2 VALUES(2, True);")
    id_inp = 2
    cont_inp = False
    conn.cursor().execute(f"""
    UPDATE test2
    SET cont = {cont_inp}
    WHERE id = {id_inp};""")
    # Result
    result = cursor.execute("SELECT * FROM test2").fetchone()
    # Assert
    assert result == (2, False)

This is the test_CRUD. I have created other tables to test the definitions but they shouldn't be saved as they are executed using the memory command.

**Comment by DevvyP** [comment]
![Image](https://user-images.githubusercontent.com/125038850/221200731-a9734f87-a1e0-4f95-883f-077a55a78cdf.png)
